config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :posts
  devise_for :users
  root to: 'home#front'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  include PublicActivity::Model
  tracked only: [:create], owner: Proc.new{ |controller, model| controller.current_user }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :validatable
         
         
  acts_as_follower
  acts_as_followable
         validates :name, presence: true
         validates :password_confirmation, presence: true
         validates :email, presence: true
         validates :remember_me, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :password_confirmation])

      devise_parameter_sanitizer.permit(:sign_in,keys:[:email, :remember_me])
    end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_commentable, only: :create
  respond_to :js

  def create
    @comment = @commentable.comments.new do |comment|
      comment.comment = params[:comment_text]
      comment.user = current_user
    end
    @comment.save
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment_id = params[:id]
    @comment.destroy
  end

  private
  def find_commentable
    @commentable_type = params[:commentable_type].classify
    @commentable = @commentable_type.constantize.find(params[:commentable_id])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
    before_action :authenticate_user!
    respond_to :js
  
    def create
      @user = User.find(params[:user_id])
      current_user.follow(@user)
    end
  
    def destroy
      @user = User.find(params[:user_id])
      current_user.stop_following(@user)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, except: :front
  respond_to :html, :js

  def index
    @post = Post.new
    @friends = @user.all_following.unshift(@user)
    @activities = PublicActivity::Activity.where(owner_id: @friends).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def front
    @activities = PublicActivity::Activity.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
  end

  def find_friends
    @friends = @user.all_following
    @users =  User.where.not(id: @friends.unshift(@user)).paginate(page: params[:page])
  end

  private
  def set_user
    @user = current_user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_likeable
    before_action :authenticate_user!
    respond_to :js
  
    def create
      @likeable.liked_by current_user
    end
  
    def destroy
      @likeable.disliked_by current_user
    end
  
    private
    def find_likeable
      @likeable_type = params[:likeable_type].classify
      @likeable = @likeable_type.constantize.find(params[:likeable_id])
    end
  end
  

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params) do |post|
      post.user = current_user
    end
    if @post.save
      redirect_to root_path
    else
      redirect_to root_path, notice: @post.errors.full_messages.first
    end
  end
 
  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:attachment, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <%= render "common/flashes" %>
  <div class="face">
    <%= profile_avatar_tag(comment.user.profile, :size36) %>
  </div>
  <div class="main">
    <%= render "comments/comment_headline", :comment => comment %>
    <div class="comment_content">
      <%= simple_format comment.content %>
    </div>
    <div class="actions">
      <%= link_to "Reply", new_comment_path(:parent_id => comment), :remote => true  %>
      <% if current_user.id == comment.user.id %>
        <span class="bullet">•</span>
        <%= link_to "Edit", edit_comment_path(comment), :remote => true %>
        <span class="bullet">•</span>
        <%= link_to "Delete", comment, :method => :delete, :remote => true, :confirm => "此评论和所有子评论都将被删除，你确定吗?" %>
      <% end %>
    </div>
    <div style="clear:both;"></div>
  </div>
  <div style="clear:both;"></div>
<% end %>

app/views/comments/_comment_headline.html.erb
<div class="headline">
  <span class="name">
    <%= link_to comment.user.profile.name, comment.user.profile %>
  </span>
  <% if comment.new_record? %>
    <span class="bullet">•</span>
    <span class="position">请输入评论内容</span>
  <% end %>
  <% unless comment.created_at.nil? %>
    <span class="bullet">•</span>
    <%= time_ago_in_words comment.created_at %>前
    <%#<%= comment.created_at.strftime("%Y-%m-%d %H:%M:%I") %>
  <% end %>
  <ul class="menu">
    <li class="collapse">
      <a href="#" data-action="collapse" title="Collapse">−</a>
    </li>
    <li class="expand" style="display:none">
      <a href="#" data-action="collapse" title="Expand">+</a>
    </li>
  </ul>
</div>

app/views/comments/_form.html.erb
<%= div_for @comment do %>
  <div class="face">
    <%= profile_avatar_tag(current_user.profile, :size36) %>
  </div>
  <div class="main">
    <%= render "comments/comment_headline", :comment => @comment %>
    <div class="comment_content">
      <%= form_for @comment, :remote => true do |f| %>
        <fieldset>
          <%= render :partial => "common/form_error", :locals => { model: @comment } %>
          <%= f.hidden_field :parent_id %>
          <%= f.hidden_field :commentable_id %>
          <%= f.hidden_field :commentable_type %>
          <div class="control-group">
            <div class="controls">
              <%= f.text_area :content, :class => 'text_area span6', :rows => 3, :onKeyDown => "javascript:return ctrl_enter_submit(event);" %>
              <div>
                <%= f.submit(@comment.new_record? ? "Post Comment" : "Update Comment", :class => "btn btn-primary") %>
                (Ctrl+Enter)
              </div>
            </div>
          </div>
        </fieldset>
      <% end %>
    </div>
    <% unless @comment.new_record? %>
      <div class="actions">
        <%= link_to "Reply", new_comment_path(:parent_id => @comment), :remote => true  %>
        <% if current_user.id == @comment.user.id %>
          <span class="bullet">•</span>
          <%= link_to "Cancel Edit", edit_comment_path(@comment), :remote => true %>
          <span class="bullet">•</span>
          <%= link_to "Delete", @comment, :method => :delete, :remote => true %>
        <% end %>
      </div>
    <% end %>
    <div style="clear:both;"></div>
  </div>
  <div style="clear:both;"></div>
<% end %>

app/views/comments/create.js.erb
<% if @comment.parent_id.present? %>
    var container = $("#<%= dom_id(@comment.parent) %>").next(".nested_comments");
<% else %>
    var container = $("#comments");
<% end %>
<% if @comment.errors.present? %>
    container.find("form").prepend("<%= escape_javascript error_messages_for(@comment) %>");
<% else %>
    container.children("#new_comment").replaceWith("<%= escape_javascript  render(@comment) + content_tag(:div, "", :class => "nested_comments") %>");
<% end %>

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript render "common/flashes" %>");

app/views/comments/edit.js.erb
if ($("#<%= dom_id(@comment) %> .comment_content form").length == 0) {
  $("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript render("form") %>");
  $("#<%= dom_id(@comment) %>").find("#comment_content")[0].focus();
} else {
  $("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript render(@comment) %>");
}

app/views/comments/index.html.erb
<%= form_tag comments_path(commentable_type: commentable.class.to_s, commentable_id: commentable.id), method: :post, remote: true do %>
  <div class="form-group">
    <%= text_area_tag :comment_text, nil, placeholder: 'Enter Comment', class: 'form-control' %>
  </div>
  <%= submit_tag :comment, class: 'btn btn-primary' %>
<% end %>

app/views/comments/new.js.erb
if ($("#comment_<%= params[:parent_id] %>").next(".nested_comments").children("#new_comment").length == 0) {
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").prepend("<%= escape_javascript render("form") %>");
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").find("#comment_content")[0].focus();
} else {
  $("#comment_<%= params[:parent_id] %>").next(".nested_comments").children("#new_comment").toggleClass('hidden');
}

app/views/comments/update.js.erb
<% if @comment.errors.present? %>
    $("#<%= dom_id(@comment) %>").find("form").prepend("<%= escape_javascript error_messages_for(@comment) %>");
<% else %>
    $("#<%= dom_id(@comment) %>").replaceWith("<%= escape_javascript  render(@comment) %>");
<% end %>

app/views/follows/_form.html.erb
<div class="follow">
<% if user.followed_by?(current_user) %>
  <%= form_tag unfollow_path(user_id: user.id), method: :post, remote: true do %>
    <%= button_tag 'unfollow', class: 'btn btn-primary' %>
  <% end %>
<% else %>
  <%= form_tag follow_path(user_id: user.id), method: :post, remote: true do %>
    <%= button_tag 'follow', class: 'btn btn-success' %>
  <% end %>
<% end %>
</div>

app/views/home/front.html.erb
<h1>Home#front</h1>
<p>Find me in app/views/home/front.html.erb</p>

<div id="activities">
  <%= render_activities(@activities)%>
<div>

app/views/home/index.html.erb
<%= form_for(@post) do |f| %>
    <div class="form-group">
      <%= f.label 'Update status' %><br>
        <%= f.text_area :content, class: 'form-control', autofocus: true, 
            placeholder: 'What\'s up?' %>
        <%= f.file_field :attachment, class: 'form-control' %>
    </div>
    <%= f.submit :post, class: 'btn btn-primary'%>
  <% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<% if current_user.liked? likeable %>
    <%= form_tag unlike_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), method: :post, remote: true do %>
      <% button_tag class: 'btn btn-block liked' do %>
        <%= fa_icon 'thumbs-up' %> unlike
      <% end %>
    <% end %>
  <% else %>
    <%= form_tag like_path(likeable_type: likeable.class.to_s, likeable_id: likeable.id), remote: true do %>
      <% button_tag class: 'btn btn-block' do %>
        <%= fa_icon 'thumbs-up' %> like
      <% end %>
    <% end %>
  <% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.text_field :attachment %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.attachment %></td>
        <td><%= post.content %></td>
        <td><%= post.user %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attachment:</strong>
  <%= @post.attachment %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>